"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var STATE_MAPPINGS;
(function (STATE_MAPPINGS) {
    STATE_MAPPINGS["MH"] = "Maharashtra";
    STATE_MAPPINGS["TN"] = "Tamil Nadu";
    STATE_MAPPINGS["AP"] = "Andhra Pradesh";
    STATE_MAPPINGS["KA"] = "Karnataka";
    STATE_MAPPINGS["DL"] = "Delhi";
    STATE_MAPPINGS["UP"] = "Uttar Pradesh";
    STATE_MAPPINGS["WB"] = "West Bengal";
    STATE_MAPPINGS["BR"] = "Bihar";
    STATE_MAPPINGS["TG"] = "Telangana";
    STATE_MAPPINGS["GJ"] = "Gujarat";
    STATE_MAPPINGS["AS"] = "Assam";
    STATE_MAPPINGS["RJ"] = "Rajasthan";
    STATE_MAPPINGS["OR"] = "Odisha";
    STATE_MAPPINGS["HR"] = "Haryana";
    STATE_MAPPINGS["MP"] = "Madhya Pradesh";
    STATE_MAPPINGS["KL"] = "Kerala";
    STATE_MAPPINGS["PB"] = "Punjab";
    STATE_MAPPINGS["JK"] = "Jammu and Kashmir";
    STATE_MAPPINGS["JH"] = "Jharkhand";
    STATE_MAPPINGS["CT"] = "Chhattisgarh";
    STATE_MAPPINGS["UT"] = "Uttarakhand";
    STATE_MAPPINGS["GA"] = "Goa";
    STATE_MAPPINGS["TR"] = "Tripura";
    STATE_MAPPINGS["PY"] = "Puducherry";
    STATE_MAPPINGS["MN"] = "Manipur";
    STATE_MAPPINGS["HP"] = "Himachal Pradesh";
    STATE_MAPPINGS["NL"] = "Nagaland";
    STATE_MAPPINGS["AR"] = "Arunachal Pradesh";
    STATE_MAPPINGS["AN"] = "Andaman and Nicobar Islands";
    STATE_MAPPINGS["LA"] = "Ladakh";
    STATE_MAPPINGS["CH"] = "Chandigarh";
    STATE_MAPPINGS["DN"] = "Dadra and Nagar Haveli and Daman and Diu";
    STATE_MAPPINGS["ML"] = "Meghalaya";
    STATE_MAPPINGS["SK"] = "Sikkim";
    STATE_MAPPINGS["MZ"] = "Mizoram";
    STATE_MAPPINGS["LD"] = "Lakshadweep";
    STATE_MAPPINGS["TT"] = "India";
})(STATE_MAPPINGS || (STATE_MAPPINGS = {}));
exports.default = STATE_MAPPINGS;
